// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Fa9V1h_GpRfXeEo56ClddRZyhFDolkE',
    appId: '1:143116400802:web:2569234dd76f7ecde93ffb',
    messagingSenderId: '143116400802',
    projectId: 'flutter-7f82f',
    authDomain: 'flutter-7f82f.firebaseapp.com',
    storageBucket: 'flutter-7f82f.appspot.com',
    measurementId: 'G-KH3R6HJMFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxxv7AkPr5kjYiS7GmgG0dQkKoNx8GgRk',
    appId: '1:143116400802:android:80d99e5d86fa3e06e93ffb',
    messagingSenderId: '143116400802',
    projectId: 'flutter-7f82f',
    storageBucket: 'flutter-7f82f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjGDe3X0Dp_khZVcnb4XFBWUAJ8BNgFRk',
    appId: '1:143116400802:ios:da7d2e90e6597075e93ffb',
    messagingSenderId: '143116400802',
    projectId: 'flutter-7f82f',
    storageBucket: 'flutter-7f82f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjGDe3X0Dp_khZVcnb4XFBWUAJ8BNgFRk',
    appId: '1:143116400802:ios:fa63a4fcaa3d982ce93ffb',
    messagingSenderId: '143116400802',
    projectId: 'flutter-7f82f',
    storageBucket: 'flutter-7f82f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
